bunker/urls.py
from django.urls import path
from django.views import generic

from . import views

app_name = "bunker"

urlpatterns = [
    # /
    path("", generic.RedirectView.as_view(url='all-orders/')),

    # /all-orders/
    path("all-orders/", views.AllOrders.as_view(), name='all_orders'),

    # /order/34/
    path("order/<int:order_id>/", views.Order.as_view(), name='order'),

    # /search/
    path("search/", views.BunkerSearch.as_view(), name="bunker_search"),
]

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [

    # shop/
    path('', views.ShopIndex.as_view(), name='index'),

    # shop/daemon-balenciaga/
    path('shoe/<slug:slug>/', views.ShoeDetail.as_view(), name='shoe'),

    # /shop/order/
    path('order/', views.CustomerOrdering.as_view(), name='order'),

    # /shop/cart/add/shoe/ | shop/cart/remove/shoe/
    path('shop/cart/<option>/<slug:slug>/', views.CartOptions.as_view(), name='cart-options'),

]

tullipos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

from . import views
from shop import views as shop_views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('favicon.ico', RedirectView.as_view(url=settings.STATIC_URL+"favicon.ico")),

    # faq/
    path('faq/', views.FAQList.as_view(), name="FAQ"),

    # faq/how-do-you-pay/
    path('faq/<slug:slug>/', views.FAQDetail.as_view(), name="FAQ-detail"),

    #
    path('', RedirectView.as_view(url=('shop/')), name='home'),

    # shop/
    path('shop/', include('shop.urls')),

    # search/
    path('search/', shop_views.Search.as_view(), name='search'),

    # bunker/
    path('bunker/', include('bunker.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/home/base.html
<!DOCTYPE html>
<html>
<head>
    {% load staticfiles %}
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock title %} | Tulliops</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/base.css' %}" />
    {% block style %}{% endblock style %}
</head>
<body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="#">Tulliops</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
              
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item {% block shop %}{% endblock %}">
                        <a class="nav-link" href="{% url 'shop:index' %}">Shop</a>
                    </li>
                    <li class="nav-item {% block faq %}{% endblock %}">
                        <a class="nav-link" href="{% url 'FAQ' %}">FAQ</a>
                    </li>
                    <li class="nav-item {% block order %}{% endblock %}">
                        <a class="nav-link" href="{% url 'shop:order' %}">order now</a>
                    </li>
                    {% if user.is_staff %}
                    <li class="nav-item {% block bunker %}{% endblock %}">
                        <a class="nav-link" href="{% url 'bunker:all_orders' %}">Bunker</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                    </li>
                    {% endif %}
                </ul>
              <form method="GET" action="{% url 'search'  %}" class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" name="query" value="{{ request.GET.query }}" placeholder="Search for shoes, brands and tags" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
              </form>
            </div>
        </nav>
    
    <div id="content">
        {% block content %}
    
        {% endblock content %}
    </div>

    <div class="container col-md-8">
        {% comment %}This is the pagination block{% endcomment %}
        {% block pagination %}
            {% if is_paginated %}
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                    {% endif %}

                    {% for i in paginator.page_range %}
                        {% if page_obj.number == i %}
                            <li class="page-item active">
                                <a href="" class="page-link">{{ i }}</a>
                            </li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}

                    {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                    {% endif %}
                </ul>
            {% endif %}
        {% endblock pagination %}
    </div>

    <!-- footer -->
    <footer class="section footer-classic context-dark bg-image" style="background: #343a40;">
            <div class="container">
              <div class="row row-30">
                <div class="col-md-4 col-xl-5">
                  <div class="pr-xl-4">
                    <p>We are shoe selling online platform, dedicated to the best services.</p>
                    <!-- Rights-->
                    <p class="rights"><span>©  </span><span class="copyright-year">2018</span><span> </span><span>Tulliops</span><span>. </span><span>All Rights Reserved.</span></p>
                  </div>
                </div>
                <div class="col-md-4">
                  <h5>Contacts</h5>
                  <dl class="contact-list">
                    <dt>email:</dt>
                    <dd><a href="mailto:#">danmburu254@gmail.com</a></dd>
                  </dl>
                  <dl class="contact-list">
                    <dt>phones:</dt>
                    <dd><a href="tel:#">0792-199-276</a> <span></a>
                    </dd>
                  </dl>
                </div>
                <div class="col-md-4 col-xl-3">
                  <h5>Tullipos</h5>
                  <ul class="nav-list">
                    <li><a href="#">About</a></li>
                    <li><a href="{% url 'shop:index' %}">Shop</a></li>
                    <li><a href="{% url 'FAQ' %}">FAQs</a></li>
                    <li><a href="{% url 'shop:order' %}">Order</a></li>
                  </ul>
                </div>
              </div>
            </div>
            <div class="row no-gutters social-container">
              <div class="col"><a class="social-inner" href="#"><span class="icon mdi mdi-facebook"></span><span>Facebook</span></a></div>
              <div class="col"><a class="social-inner" href="#"><span class="icon mdi mdi-instagram"></span><span>instagram</span></a></div>
              <div class="col"><a class="social-inner" href="#"><span class="icon mdi mdi-twitter"></span><span>twitter</span></a></div>
              <div class="col"><a class="social-inner" href="#"><span class="icon mdi mdi-youtube-play"></span><span>google</span></a></div>
            </div>
          </footer>

    
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/base.js' %}"></script>
    {% block script %}{% endblock script %}
</body>
</html>

templates/home/faq_detail.html
{% extends "home/base.html" %}

{% block title %}{{ faq.question }}{% endblock title %}

{% block faq %}active{% endblock %}

{% block content %}
    <div class="container">
        <div>
            <h1>{{ faq.question }}</h1>
            <div class="list-inline">
                {% for tag in faq.tag.all %}
                    <span class="text-success">{{ tag.name }} |</span>
                {% endfor %}
            </div>
        </div>
        <hr>
        <div class="container">
            <p class="col-md-10 text-secondary">{{ faq.answer }}</p>
        </div>
    </div>
{% endblock content %}

templates/home/faq_list.html
{% extends "home/base.html" %}
{% load staticfiles %}
{% block title %}All FAQ{% endblock title %}
{% block style %}<link rel="stylesheet" type="text/css" href="{% static 'css/faq.css' %}" >{% endblock style %}
{% block faq %}active{% endblock %}

{% block content %}

<div class="container">
    <h1>Frequently Asked Questions</h2>
    <hr>
    
    <div class="col-md-6" id="questions">
        {% for faq in questions %}
            <div class="faq-question">
                <h4 class="lead text-primary">{{ faq.question }}</h4>
                <p class="faq-question-answer">{{ faq.answer|truncatechars:200 }}<a href="{{ faq.get_absolute_url }}">Read More</a></p>
                <ul class="list-inline">
                    {% for tag in faq.tag.all %}
                        <li class="text-success list-inline-item">{{ tag.name }} |</li>
                    {% endfor %}
                </ul>
            </div>
            <hr>
        {% endfor %}
    </div>
</div>

{% endblock content %}