bunker/urls.py
from django.urls import path
from django.views import generic

from . import views

app_name = "bunker"

urlpatterns = [
    # /
    path("", generic.RedirectView.as_view(url='all-orders/')),

    # /all-orders/
    path("all-orders/", views.AllOrders.as_view(), name='all_orders'),

    # /order/34/
    path("order/<int:order_id>/", views.Order.as_view(), name='order'),

    # /search/
    path("search/", views.BunkerSearch.as_view(), name="bunker_search"),
]

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [

    # shop/
    path('', views.ShopIndex.as_view(), name='index'),

    # shop/daemon-balenciaga/
    path('shoe/<slug:slug>/', views.ShoeDetail.as_view(), name='shoe'),

    # /shop/order/
    path('order/', views.CustomerOrdering.as_view(), name='order'),

    # /shop/cart/add/shoe/ | shop/cart/remove/shoe/
    path('shop/cart/<option>/<slug:slug>/', views.CartOptions.as_view(), name='cart-options'),

]

tullipos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

from . import views
from shop import views as shop_views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('favicon.ico', RedirectView.as_view(url=settings.STATIC_URL+"favicon.ico")),

    # faq/
    path('faq/', views.FAQList.as_view(), name="FAQ"),

    # faq/how-do-you-pay/
    path('faq/<slug:slug>/', views.FAQDetail.as_view(), name="FAQ-detail"),

    #
    path('', RedirectView.as_view(url=('shop/')), name='home'),

    # shop/
    path('shop/', include('shop.urls')),

    # search/
    path('search/', shop_views.Search.as_view(), name='search'),

    # bunker/
    path('bunker/', include('bunker.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bunker/models.py
from django.db import models

# Create your models here.

bunker/views.py
from django.views import View
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from django.utils.datastructures import MultiValueDictKeyError
from django.db.models import Q

from shop.models import CustomerOrder


class AllOrders(View):
    def get(self, *args, **kwargs):
        if not self.request.user.is_staff:
            raise Http404

        orders = CustomerOrder.objects.order_by('-created')
        return render(self.request, 'bunker/all_orders.html', {
            'orders': orders,
        })


class Order(View):
    def get(self, *args, **kwargs):
        if not self.request.user.is_staff:
            raise Http404

        order = get_object_or_404(CustomerOrder, pk=kwargs['order_id'])
        return render(self.request, 'bunker/order.html', {
            'order': order,
        })


class BunkerSearch(View):
    def get(self, *args, **kwargs):
        if not self.request.user.is_staff:
            raise Http404

        try:
            query_term = self.request.GET['query']
        except MultiValueDictKeyError:
            query_term = ''


        q_set = (
            Q(preferred_name__icontains=query_term) |
            Q(phone_number__icontains=query_term) |
            Q(residence__icontains=query_term)
        )

        orders = CustomerOrder.objects.filter(q_set)

        return render(self.request, 'bunker/all_orders.html', {
            'search': True,
            'query': query_term,
            'orders': orders,
        })

bunker/templates/bunker/all_orders.html
{% extends "home/base.html" %}
{% load staticfiles %}
{% block title %}All Orders{% endblock title %}

{% block bunker %}active{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'bunker/css/all_orders.css'%}">
{% endblock style %}

{% block content %}

<div class="container" id="main-order-page">
    <h1 class="text-center">{% if search %}Search results for "{{ query }}" {%else %} All Orders{% endif %}</h1>
    <hr>
    
    <div class="row">
        <!-- Staff details -->
        <div class="col-md-3">
            <h3>Staff Details</h3>
            <ul id="staff-details">
                <li><strong>Staff Name</strong>: {{user.username}}</li>
                <li><strong>Date Joined</strong>: {{ user.date_joined}}</li>
            </ul>
            <hr>
            <form method="GET" id="order-search" action="{% url 'bunker:bunker_search' %}">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="search orders" value="{{ query }}" name='query'>
                </div>
                <div class="form-group text-center">
                    <input type="submit" class="btn btn-dark" value="search" >
                </div>
            </form>

            <div class="alert alert-info">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <strong>Searching</strong> You can search by use of preferred name, phone number, rescidency.
            </div>

        </div>
    
        <!-- all orders -->
        <div class="col-md-9" id="orders-section">
            {% if orders.count == 0 %}
                <h2 class="text center">{% if search %}Sorry no results for {{ query }}.{% else %}Sorry, no orders at this time.{% endif %}</h2>
            {% else %}
                {% for order in orders %}
                    <a class="order-link" href="{% url 'bunker:order' order.id %}">
                    <div class="order alert">
                        <div class="row">
                            <span class="col-xl-6"><strong>Order made by </strong>{{ order.preferred_name }}</span>
                            <span class="col-xl-6"><strong>Order made </strong> {{ order.created }}</span>
                        </div>
                        <div class="row">
                            <span class="col-xl-6"><strong>Total order at </strong> KSH. {{ order.total_amount }}</span>
                            <span class="col-xl-6"><strong>{{ order.shoes_ordered.count }}</strong> shoes ordered</span>
                        </div>
                    </div>
                    </a>
                {% endfor %}
            {% endif %}
            
        </div>
    </div>

</div>


{% endblock content %}

bunker/templates/bunker/order.html
{% extends "home/base.html" %}
{% load staticfiles %}
{% comment %} {% load admin_urls %} {% endcomment %}
{% block title %}Order by {{order.preferred_name}}{% endblock title %}

{% block style %}
<link rel="stylesheet" href="{% static 'bunker/css/order.css' %}">
{% endblock style %}

{% block bunker %}active{% endblock bunker %}

{% block content %}

<div class="container" id="order-page">
    <h1 class="text-center">Order Details for {{ order.preferred_name }}'s order</h1>
    <hr>
    <div class="row">
        <!-- Order details -->
        <div class="col-md-5" id="order-details">
            <h2 class="text-center">Details</h2>
            <hr>
            <h4>Personal</h4>
            <ul>
                <li><strong>Name</strong>:<span class="detail-info">{{ order.preferred_name }}</span></li>
                <li><strong>Phone Number</strong>:<span class="detail-info">{{ order.phone_number }}</span></li>
                <li><strong>Rescidence</strong>:<span class="detail-info">{{ order.residence }}</span></li>
            </ul>
            <hr>
            <h4>order</h4>
            <ul>
                <li><strong>Created</strong>:<span class="detail-info">{{ order.created }}</span></li>
                <li><strong>Total shoes</strong>:<span class="detail-info">{{ order.shoes_ordered.count }}</span></li>
                <li><strong>Total Amount Due</strong>:<span class="detail-info"> KSH. {{ order.total_amount }}</span></li>
            </ul>
        </div>

        <div class="col-md-7" id="all-shoes">
            <h2>Shoes ordered</h2>
            <hr>
            {% for shoe in order.shoes_ordered.all %}
            <div class="shoe">
                <div class="row">
                    <img class="col-sm-5" src="{{ shoe.get_main_image.image.url }}" alt="{{ shoe.get_main_image.image.description }}">
                    <div class="col-sm-7">
                        <ul>
                            <li class="shoe-detail"><a href="{{ shoe.get_absolute_url }}">{{ shoe.name }}</a></li>
                            <li class="shoe-detail">{{ shoe.brand }}</li>
                            <li class="shoe-detail">KSH. {{ shoe.price }}</li>
                        </ul>
                    </div>
                </div>
            </div>   
            {% endfor %}         
        </div>
    </div>

    {% if user.is_superuser %}
        <div class="container text-center" id="delete-order">
            
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <strong>Be aware</strong> Deleting an order makes all the shoes availabe in the shop! Are you sure?
            </div>

            
            <a href="{% url 'admin:shop_customerorder_delete' order.pk %}" type="button" class="btn btn-danger">Delete order by {{ order.preferred_name }}</a>
            
            
        </div>
    {% endif %}



</div>










{% endblock content %}