shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [

    # shop/
    path('', views.ShopIndex.as_view(), name='index'),

    # shop/daemon-balenciaga/
    path('shoe/<slug:slug>/', views.ShoeDetail.as_view(), name='shoe'),

    # /shop/order/
    path('order/', views.CustomerOrdering.as_view(), name='order'),

    # /shop/cart/add/shoe/ | shop/cart/remove/shoe/
    path('shop/cart/<option>/<slug:slug>/', views.CartOptions.as_view(), name='cart-options'),

]

tullipos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

from . import views
from shop import views as shop_views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('favicon.ico', RedirectView.as_view(url=settings.STATIC_URL+"favicon.ico")),

    # faq/
    path('faq/', views.FAQList.as_view(), name="FAQ"),

    # faq/how-do-you-pay/
    path('faq/<slug:slug>/', views.FAQDetail.as_view(), name="FAQ-detail"),

    #
    path('', RedirectView.as_view(url=('shop/')), name='home'),

    # shop/
    path('shop/', include('shop.urls')),

    # search/
    path('search/', shop_views.Search.as_view(), name='search'),

    # bunker/
    path('bunker/', include('bunker.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

import re


def slug_processor(slug):
    return "-".join(slug.split(" ")).lower()


class Tag(models.Model):
    name = models.CharField(max_length=20)
    for_shoe = models.BooleanField(default=True)
    objects = models.Manager()

    def __str__(self):
        return self.name


class ShoeManager(models.Manager):
    @staticmethod
    def get_brands():
        shoes = Shoe.objects.all()
        brands = []
        for shoe in shoes:
            if shoe.brand not in brands:
                brands.append(shoe.brand)
        return brands

    def get_filtered_brands(self, term):
        all_brands = self.get_brands()
        filtered_brands = []

        for brand in all_brands:
            if re.search(r'{}'.format(term), brand, re.M | re.I):
                filtered_brands.append(brand)

        return filtered_brands


class ShoeQuerySet(models.QuerySet):
    def total_price(self):
        return sum([
            shoe.price for shoe in self
        ])


class Shoe(models.Model):
    genders = (('M', 'male'), ('F', 'female'), ('U', 'unisex'))
    name = models.CharField(max_length=50)
    slug = models.SlugField(
        help_text="how do you want the url to appear don't edit. An automatic one is generated from name",
        blank=True
    )
    size = models.IntegerField()
    color = models.CharField(max_length=100)
    brand = models.CharField(max_length=50)
    sex = models.CharField(max_length=2, choices=genders)
    available = models.BooleanField(default=True)
    rating = models.IntegerField(default=0)
    tags = models.ManyToManyField(Tag)
    description = models.TextField(blank=True)
    price = models.BigIntegerField(default=0.00)
    objects = ShoeManager.from_queryset(ShoeQuerySet)()

    class Meta:
        ordering = ['-id']

    def save(self, *args, **kwargs):
        self.slug = slug_processor(str(self.name))
        return super().save(args, kwargs)

    def get_absolute_url(self):
        return reverse('shop:shoe', args=[self.slug])

    def get_sex(self):
        if self.sex == "M":
            return self.genders[0][-1]
        elif self.sex == "F":
            return self.genders[1][-1]
        else:
            return self.genders[-1][-1]

    def get_main_image(self):
        return self.shoeimage_set.filter(main=True)[0]

    def __str__(self):
        return self.name


class ShoeImage(models.Model):
    shoe = models.ForeignKey(Shoe, on_delete=models.CASCADE, blank=True, null=True)
    image = models.ImageField(
        upload_to="shoes/",
        help_text='please make sure the image is in a ratio of 16:9'
    )
    description = models.TextField()
    main = models.BooleanField(
        default=False,
        help_text='Mark at-least one as main(important)'
    )
    objects = models.Manager()

    def __str__(self):
        return "Image for {}".format(self.shoe)


class CustomerOrder(models.Model):
    preferred_name = models.CharField(max_length=50, help_text='Enter the name you would like us to refer to you by')
    phone_number = models.CharField(max_length=10, help_text='Enter a valid Kenyan number starting with \'07\'')
    residence = models.CharField(max_length=50, help_text='Where would you like to get your order')
    shoes_ordered = models.ManyToManyField(Shoe)
    cleared = models.BooleanField(default=False)
    cancelled = models.BooleanField(default=False)
    session_id = models.IntegerField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    objects = models.Manager()

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return "Order by {}".format(self.preferred_name)

    def get_absolute_url(self):
        return reverse('bunker:order', args=[str(self.id)])

    def total_amount(self):
        return self.shoes_ordered.all().total_price()

    def delete(self, *args, **kwargs):
        # make all shoes available
        for shoe in self.shoes_ordered.all():
            shoe.available = True
            shoe.save()
        return super().delete()


class FAQ(models.Model):
    question = models.CharField(max_length=400)
    slug = models.SlugField(blank=True)
    answer = models.TextField()
    tag = models.ManyToManyField(Tag)
    objects = models.Manager()

    class Meta:
        ordering = ['-id']

    def save(self, *args, **kwargs):
        self.slug = slugify(self.question)
        return super().save(args, kwargs)

    def get_absolute_url(self):
        return reverse('FAQ-detail', args=[self.slug])

    def __str__(self):
        return self.question

shop/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.core.validators import ValidationError

import re

from .models import CustomerOrder


class UserFeedBackForm(forms.Form):
    feedback = forms.CharField(max_length=500, widget=forms.Textarea)
    email = forms.EmailField(widget=forms.EmailInput, help_text='This is required but will never be used')


class CustomerOrderForm(forms.ModelForm):
    class Meta:
        model = CustomerOrder
        fields = ('preferred_name', 'phone_number', 'residence',)

    def clean_phone_number(self):
        data = self.cleaned_data['phone_number']
        if len(data) != 10:
            raise ValidationError(_('The phone number is not valid (not 10 digits)'), code='Less Than 10')

        if not re.search(r'^07\d{8}', data):
            raise ValidationError(_('This is not a valid number'), code='not 07..')

        return data

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.db.models import ObjectDoesNotExist, Q
from django.views import View, generic
from django.http import JsonResponse
from django import forms

from .models import Shoe, Tag, FAQ
from .forms import CustomerOrderForm

import re


# all shoes
class ShopIndex(generic.ListView):
    model = Shoe
    template_name = 'shop/shoe_list.html'
    context_object_name = 'shoes'
    paginate_by = 20

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['brands'] = Shoe.objects.get_brands()[:5]
        context['cart'] = self.request.session.setdefault('cart', [])
        context['tags'] = Tag.objects.filter(for_shoe=True)[:3]
        return context


# each shoe
class ShoeDetail(generic.DetailView):
    model = Shoe
    template_name = 'shop/shoe.html'
    context_object_name = 'shoe'
    slug_url_kwarg = 'slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        try:
            liked = self.request.session['liked_brands']
            liked.append(context['shoe'].brand)
            self.request.session['liked_brands'] = liked
        except KeyError:
            self.request.session['liked_brands'] = []
            self.request.session['liked_brands'].append(context['shoe'].brand)
        context['shoes'] = Shoe.objects.all()
        context['cart'] = self.request.session['cart']
        if context['shoe'].id in context['cart']:
            context['in_cart'] = True
        else:
            context['in_cart'] = False
        return context


# customer ordering
class CustomerOrdering(View):
    form = CustomerOrderForm
    template_name = 'shop/order.html'
    
    def get(self, request):
        cart = request.session.setdefault('cart', [])
        cart = Shoe.objects.filter(pk__in=cart)
        form = CustomerOrderForm

        for item in form.base_fields.values():
            item.widget = forms.TextInput(attrs={"class": "form-control"})

        return render(request, self.template_name, {
            'form': form,
            'cart': cart,
        })

    def post(self, request):
        form = CustomerOrderForm(request.POST)
        shoe_list = request.session.get('cart')

        if form.is_valid():
            form.save()
            # add every shoe to ordered for the order
            for i in shoe_list:
                try:
                    shoe = Shoe.objects.get(id=i)
                    shoe.available = False
                    shoe.save()
                    form.instance.shoes_ordered.add(shoe)
                except ObjectDoesNotExist:
                    continue
            form.instance.save()
            if len(form.instance.shoes_ordered.all()) < 1:
                form.instance.delete()
                return redirect(reverse('shop:order'))
            request.session['cart'] = []
        else:
            return render(request, self.template_name, {
                'form': form,
                'cart': self.get_shoes_in_cart(shoe_list)
            })

        return render(request, self.template_name, {
            'post_post': True,
        })


# cart options
class CartOptions(View):
    @staticmethod
    def post(request, **kwargs):
        response = dict()
        cart = request.session.get('cart')
        shoe = get_object_or_404(Shoe, slug=kwargs['slug'])

        if kwargs['option'] == 'add':
            if shoe.id not in cart:
                cart.append(shoe.id)
            request.session['cart'] = cart
            response = {'success': True, 'message': '{} added to cart'.format(shoe.name)}

        elif kwargs['option'] == 'remove':
            cart.remove(shoe.id)
            request.session['cart'] = cart
            response = {'success': True, 'message': '{} removed from cart'.format(shoe.name)}

        else:
            response['success'] = False
            response['text'] = '{} is not supported'

        return JsonResponse(response)


class Search(generic.TemplateView):
    template_name = 'shop/search.html'
    males = ['M', 'MALE', 'MALES', 'MEN', 'BOYS', 'BOY']
    females = ['F', 'FEMALE', 'FEMALES', 'WOMEN', 'GIRLS', 'GIRL']
    tag_names = ['SPORT', 'CASUAL', 'OFFICIAL', 'PARTY']

    @staticmethod
    def search_shoes(term):
        q_set_shoes = (
            Q(name__icontains=term) |
            Q(brand__icontains=term) |
            Q(tags__name__icontains=term)
        )

        return {
            'shoes': Shoe.objects.filter(q_set_shoes),
            'brands': Shoe.objects.get_filtered_brands(term),
            'faq': FAQ.objects.filter(question__icontains=term)
        }

    def master_search(self, query):
        results = dict()
        special_search_feature = None

        # if a key key is added to search term 'brand:nike' extract key and make search special
        if re.search(r'\w+:\w+', query, re.M | re.I):
            special_search = True
            special_search_feature = re.findall(r'\w+', query, re.M | re.I)[0]
            query_term = re.findall(r':\w+', query, re.M | re.I)[0].split(':')[-1]

        # if not key make a normal search
        else:
            special_search = False
            query_term = query

        # special search
        if special_search:
            if special_search_feature == 'brand':
                results['shoes'] = Shoe.objects.filter(brand__icontains=query_term)
                results['brands'] = Shoe.objects.get_filtered_brands(query_term)

            elif special_search_feature == 'color':
                results['shoes'] = Shoe.objects.filter(color=query_term)

            elif special_search_feature == 'faq':
                results['faq'] = FAQ.objects.filter(question__icontains=query_term)

            elif special_search_feature == 'size':
                results['shoes'] = Shoe.objects.filter(size=int(query_term))

            elif special_search_feature == 'price':
                pass

            elif special_search_feature == 'sex' or special_search_feature == 'gender':
                key = None
                if query_term.upper() in self.males:
                    key = 'M'
                elif query_term.upper() in self.females:
                    key = 'F'
                elif query_term.upper() == 'ALL' or query_term.upper() == 'UNISEX':
                    key = 'U'

                results['shoes'] = Shoe.objects.filter(sex=key)

            elif special_search_feature == 'tag':
                results['shoes'] = Shoe.objects.filter(tags__name__icontains=query_term)
                results['faq'] = FAQ.objects.filter(tag__name__icontains=query_term)

            else:
                results['message'] = 'No such filter as {}'.format(special_search_feature)

            results['feature'] = special_search_feature
            results['term'] = query_term

        # normal search
        else:
            results = self.search_shoes(query_term)

        return results

    def get(self, request, *args, **kwargs):
        raw_query = request.GET['query']
        results = self.master_search(raw_query)

        return render(request, self.template_name, {
            'results': results,
            'cart': request.session.setdefault('cart', []),
            'query': raw_query
        })

shop/templates/shop/absolute_shoe.html
{% load staticfiles %}
<div class="card shoe">
    <img class="card-img-top" alt="{{ shoe.get_main_image.description }}" src="{{ shoe.get_main_image.image.url }}">
    <div class="card-body">
        <h5 class="card-title"><a href="{{ shoe.get_absolute_url }}">{{ shoe.name }}</a></h5>
        <hr>
        <div class="card-text">
            <div class="row">
                <p class="col-xl-4 text-info">Ksh.{{ shoe.price }}</p>
                <div class="col-xl-4">Size {{ shoe.size }}</div>
                <div class="col-xl-4">
                    {% if shoe.available %}
                        available
                    {% else %}
                        not available
                    {% endif %}
                </div>
            </div>
            <div class="row">
                {% csrf_token %}
                <span class="text-dark col-md-10">by <a href="{% url 'search' %}?query=brand:{{ shoe.brand }}">{{ shoe.brand }}</a></span>
                {% if shoe.available %}
                    {% if shoe.id in cart %}
                        <span data-page="list" data-url="{% url 'shop:cart-options' 'add' shoe.slug %}" data-url-remove="{% url 'shop:cart-options' 'remove' shoe.slug %}" class="cart-button-remove" data-toggle="tooltip" data-placement="bottom" title="Remove from cart"><img src="{% static 'svg/remove_shopping_cart_24px.svg' %}" alt="add to cart"/></span>
                    {% else %}
                        <span data-page="list" data-url="{% url 'shop:cart-options' 'add' shoe.slug %}" data-url-remove="{% url 'shop:cart-options' 'remove' shoe.slug %}" class="cart-button" data-toggle="tooltip" data-placement="bottom" title="add to cart"><img src="{% static 'svg/add_shopping_cart_24px.svg' %}" alt="add to cart"/></span>
                    {% endif %}  
                {% endif %}
            </div>
        </div>
    </div>
    <div class="card-footer">
        <span>tags:
        {% for tag in shoe.tags.all %}
            <small class="text-muted"><a href="{% url 'search' %}?query=tag:{{ tag }}" class="">{{ tag }}</a></small> |
        {% endfor %}
        </span>
        {% if shoe.id in cart %}
            <span class="in-cart text-info"><a class="text-warning" href="{% url 'shop:order' %}">in cart</a></span>
        {% else %}
            <span style="display: none;" class="in-cart text-info"><a class="text-warning" href="{% url 'shop:order' %}">in cart</a></span>
        {% endif %}
    </div>
</div>

shop/templates/shop/order.html
{% extends "home/base.html" %}
{% load staticfiles %}
{% block title %}Order now{% endblock title %}
{% block style %}<link rel="stylesheet" type="text/css" href="{% static 'shop/css/order.css' %}">{% endblock style %}
{% block order %}active{% endblock order %}

{% block content %}
<div class="container">
    {% if post_post %}
        <div class="container col-md-7 text-center alert alert-success success-order">
            <h2>Your order has been made</h2>
            <hr>
            <p class="lead text-info">You will receive a call from <strong>0794-904-435</strong> within 3 hours to get more details on how you will receive your shoes. Thank you for Choosing Tullipos <a href="{% url 'shop:index' %}" class="btn btn-link">shop more</a></p>
        </div>
    {% else %}
        <div class="row">
            <div class="col-md-4">
                {% if cart %}
                    <h3>Your cart Items</h3>
                    <div id="no-items-inc" style="margin-top: 5em; display: none;" class="alert alert-success">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        <strong>No items on cart!</strong><p>You have no items in your cart <br /><a href="{% url 'shop:index' %}">Add now</a></p>
                    </div>
                    <hr id="top-cart-line">
                    {% for shoe in cart %}
                        <div>
                            <div class="shoe row">
                                <div class="col-xl-5">
                                    <h5 class="lead"><a href="{{ shoe.get_absolute_url }}">{{ shoe.name }}</a></h5>
                                    <span class="text-dark">Ksh. {{ shoe.price }}</span>
                                </div>
                                <div class="col-xl-7">
                                    {% csrf_token %}
                                    <div data-page='cart' data-url="{% url 'shop:cart-options' 'add' shoe.slug %}" data-url-remove="{% url 'shop:cart-options' 'remove' shoe.slug %}" class="cart-button-remove" onclick="updateCartPrice({{shoe.price}})">
                                        <img data-placement="top" data-toggle="tooltip" title="remove from cart" src="{% static 'svg/remove_shopping_cart_24px.svg' %}">
                                    </div>
                                </div>
                            </div>
                            <hr/>
                        </div>
                    {% endfor %}

                <h2>Total: KSH. <span id="cart-total">{{ cart.total_price }}</span></h2>
                {% else %}
                    <div style="margin-top: 5em" class="alert alert-success">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        <strong>No items on cart!</strong><p>You have no items in your cart <br /><a href="{% url 'shop:index' %}">Add now</a></p>
                    </div>
                    
                {% endif %}
            </div>

            <div class="col-md-8">
                <h3 id="form-title">Make Your order now</h3>
                <hr>

                <form method="POST" class="form col-md-10" id="order-form" autocomplete="off">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="row">
                            <div style="max-width: 66%" class="col-xl-8 form-group">
                                {% if field.errors %}
                                    {% for error in field.errors %}
                                        <div class="alert alert-danger">
                                            <p>{{ error }}</p>
                                        </div>
                                    {% endfor %}
                                {% endif %}
                                <label>{{ field.label }}</label>
                                {{ field }}
                            </div>
                            <div class="col-xl-4">
                                {% if field.help_text %}
                                    <div class="alert alert-info">
                                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                        {{ field.help_text }}
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                        <hr>
                    {% endfor %}
                    <div class="form-group">
                        <button type="submit" class="btn btn-info">order</button>    
                    </div>
                </form>

            </div>
        </div>
    {% endif %}
</div>
{% endblock content %}

{% block script %}<script src="{% static 'shop/js/order.js' %}"></script>
<script src="{% static 'shop/js/shoe.js' %}"></script>{% endblock script %}

shop/templates/shop/search.html
{% extends "home/base.html" %}
{% load staticfiles %}
{% block title %}Search{% endblock title %}
{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'shop/css/shoe_list.css' %}"/>
<link rel="stylesheet" type="text/css" href="{% static 'shop/css/search.css' %}"/>
{% endblock style %}
{% block shop %}active{% endblock shop %}


{% block content %}
<div class="container-fluid">
    {% if results.message %}
        <h1 class="main-heading">{{ results.message }}</h1>
        <a href="" style="margin-left: 20%;" class="btn btn-link">learn more</a>
    {% else %}
        <h1 class="main-heading">Search results from '{{ query }}'</h1>
    {% endif %}
    <hr>

    {% if results.shoes %}
        {% comment %}shoes results{% endcomment %}
        <h2 class="section-heading">results for shoes {% if results.feature %} of {{ results.feature }} '{{ results.term }}'{% endif %}</h2>

        <div class="container col-md-10"><hr></div>
        <div class="row">
            {% for shoe in results.shoes %}
                {% include "shop/absolute_shoe.html" %}
            {% endfor %}
        </div>
    {% endif %}

    {% if results.brands %}
        {% comment %}brand results{% endcomment %}
        <h2 class="section-heading">results for brands</h2>
        <div class="container col-md-10"><hr></div>

        <div class="row">
            {% for brand in results.brands  %}
                <div class="col-md-2 brand-top">
                    <div class="card brand">
                        <img class="card-img-top" alt="imge for {{ brand }}" src="http://127.0.0.1/images/new/surface_studio.jpg"/>
                        <div class="card-body">
                            <h3 class="card-title">{{ brand }}</h3>
                            <div class="card-text">
                                <a href="{% url 'search' %}?query=brand:{{ brand }}" class="btn btn-link">see shoes</a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endif %}


    {% if results.faq %}
        {% comment %}FAQs results{% endcomment %}
        <h2 class="section-heading">results for Frequently Asked Questions</h2>

        <div class="container col-md-10"><hr></div>
        <div class="container col-md-8">
            <ul class="list-group">
                {% for f in results.faq %}
                    <div class="list-group-item faqs-results">
                        <h5 class="lead">{{ f.question }}</h5>
                        <li class="list-inline">
                            {% for tag in f.tag.all %}
                                <li class="list-inline-item">{{ tag }} |</li>
                            {% endfor %}
                        </li>
                        <a href="{{ f.get_absolute_url }}" class="btn btn-link">see</a>
                    </div>
                {% endfor %}
            </ul>
        </div>
    {% endif %}

</div>
{% endblock content %}

shop/templates/shop/shoe.html
{% extends "home/base.html" %}
{% load staticfiles %}
{% block title %}{{ shoe.name }}{% endblock title %}
{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'shop/css/shoe_list.css' %}"/>
<link rel="stylesheet" type="text/css" href="{% static 'shop/css/shoe.css' %}"/>
{% endblock style %}
{% block shop %}active{% endblock shop %}

{% block content %}
<div id="shoe">
    <div class="container-fluid" id="top-layer">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-3">
                <span class="text-primary">Filter by <a href="{% url 'search' %}?query=sex:{{shoe.get_sex}}" class="btn btn-dark">{{ shoe.get_sex }}</a></span>
            </div>
            <div class="col-md-3">
                <span class="text-primary">Filter by <a href="{% url 'search' %}?query=brand:{{shoe.brand}}" class="btn btn-dark">{{ shoe.brand }}</a></span>
            </div>
            <div class="col-md-3 list-inline">
                <span class="text-primary">Filter by </span>
                {% for tag in shoe.tags.all %}
                    <a href="{% url 'search' %}?query=tag:{{tag}}" class="btn btn-dark list-inline-item">{{ tag }}</a>
                {% endfor %}
            </div>
        </div>
    </div>
    <hr>

    <div class="shoe-details row">
        <div class="col-md-6">
            <div class="shoe-image">
                <img alt="{{ shoe.get_main_image.description }}" src="{{ shoe.get_main_image.image.url }}">
            </div>
            <hr>
            <div class="shoe-description container col-md-10">
                <h2>{{ shoe.name }}</h2>
                <p class="text-primary">{{ shoe.description }}</p>
                <hr>
                
                
                <li class="list-inline">
                    <li class="list-inline-item text-info">Rating</li>
                    <li id="1" class="list-inline-item"><img class="rating-star" src="{% static 'svg/star_border_24px.svg' %}"></li>
                    <li id="2" class="list-inline-item"><img class="rating-star" src="{% static 'svg/star_border_24px.svg' %}"></li>
                    <li id="3" class="list-inline-item"><img class="rating-star" src="{% static 'svg/star_border_24px.svg' %}"></li>
                    <li id="4" class="list-inline-item"><img class="rating-star" src="{% static 'svg/star_border_24px.svg' %}"></li>
                    <li id="5" class="list-inline-item"><img class="rating-star" src="{% static 'svg/star_border_24px.svg' %}"></li>
                </li>
            </div>
        </div>

        <div class="col-md-4">
            <ul id="details-shoe" class="list-group">
                <li class="list-group-item">Price: <span class="text-info">Ksh.{{ shoe.price }}</span></li>
                {% if shoe.available %}
                    <li class="list-group-item"><span class="text-info">available</span></li>
                {% else %}
                    <li class="list-group-item"><span class="text-info">not available</span></li>
                {% endif %}
                <li class="list-group-item">Brand: <span class="text-info">{{ shoe.brand }}</span></li>
                <li class="list-group-item">Gender: <span class="text-info">{{ shoe.get_sex }}</span></li>
                <li class="list-group-item">Size: <span class="text-info">{{ shoe.size }}</span></li>
                <li class="list-group-item">Colour: <span class="text-info">{{ shoe.color }}</span></li>
            </ul>

            <div class="actions container">
                {% csrf_token %}
                {% if shoe.available %}
                    {% if in_cart %}
                        <div id="cart" data-page="detail" data-placement="top" data-toggle="tooltip" title="Remove {{ shoe.name }} from cart" class="cart-button-remove" data-url="{% url 'shop:cart-options' 'add' shoe.slug %}" data-url-remove="{% url 'shop:cart-options' 'remove' shoe.slug %}">
                            <img src="{% static 'svg/remove_shopping_cart_24px.svg' %}">
                        </div>
                    {% else %}
                        <div id="cart" data-page="detail" data-placement="top" data-toggle="tooltip" title="add {{ shoe.name }} to cart (Ksh.{{ shoe.price }})" class="cart-button" data-url="{% url 'shop:cart-options' 'add' shoe.slug %}" data-url-remove="{% url 'shop:cart-options' 'remove' shoe.slug %}">
                            <img src="{% static 'svg/add_shopping_cart_24px.svg' %}">
                        </div>
                    {% endif %}
                {% endif %}
                <div class="">
                    <h6 class="text-info" style="display: none">in cart</h6>
                </div>
            </div>
        </div>
    </div>

    <hr>

    <div class="more container">
        <h2>more shoes</h2>
        <hr>
        <div class="row">
            {% include "shop/shoes.html" %}
        </div>
    </div>

</div>
{% endblock content %}

{% block script %}<script src="{% static 'shop/js/shoe.js' %}"></script>{% endblock script %}

shop/templates/shop/shoes.html
{% for shoe in shoes %}
	{% if shoe.available %}
    	{% include "shop/absolute_shoe.html" %}
	{% endif %}
{% endfor %}